# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedData',
            fields=[
                ('Código', models.IntegerField(primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(max_length=200)),
                ('SUBRUBRO', models.CharField(max_length=200)),
                ('RUBRO', models.CharField(max_length=200)),
                ('MARCA_P', models.CharField(max_length=200)),
                ('EDAD', models.CharField(max_length=200)),
                ('CONSIDER', models.CharField(max_length=200)),
                ('GRUPO', models.CharField(max_length=200)),
                ('Peso', models.FloatField()),
                ('MATERIAL', models.CharField(max_length=200)),
                ('TIPO_P', models.CharField(max_length=200)),
                ('USO', models.CharField(max_length=200)),
                ('TAMANO', models.CharField(max_length=200)),
                ('URLFOTO1', models.CharField(max_length=200)),
                ('URLFOTO2', models.CharField(max_length=200)),
                ('URLFOTO3', models.CharField(max_length=200)),
                ('Precio', models.FloatField()),
                ('Stock', models.IntegerField()),
                ('LISTAPRE', models.CharField(max_length=200)),
                ('TITUMELI', models.CharField(max_length=200)),
                ('GRUPO_RECA', models.CharField(max_length=200)),
                ('DESC_LAR', models.CharField(max_length=200)),
            ],
        ),
    ]
