# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_test', '0008_auto_20170115_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importeddata',
            name='CONSIDER',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importeddata',
            name='DESC_LAR',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importeddata',
            name='DETALLE',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importeddata',
            name='EDAD',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importeddata',
            name='GRUPO',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importeddata',
            name='GRUPO_RECA',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importeddata',
            name='LISTAPRE',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importeddata',
            name='MARCA_P',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importeddata',
            name='MATERIAL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importeddata',
            name='RUBRO',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importeddata',
            name='SUBRUBRO',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importeddata',
            name='TAMANO',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importeddata',
            name='TIPO_P',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importeddata',
            name='TITUMELI',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importeddata',
            name='URLFOTO1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importeddata',
            name='URLFOTO2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importeddata',
            name='URLFOTO3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importeddata',
            name='USO',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
