# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_test', '0009_auto_20170115_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guests',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
